/*
 * generated by Xtext 2.21.0
 */
package org.xtext.htwg.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.htwg.parser.antlr.internal.InternalLitManParser;
import org.xtext.htwg.services.LitManGrammarAccess;

public class LitManParser extends AbstractAntlrParser {

	@Inject
	private LitManGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalLitManParser createParser(XtextTokenStream stream) {
		return new InternalLitManParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "LitMan";
	}

	public LitManGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LitManGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
