/*
 * generated by Xtext 2.21.0
 */
package org.xtext.htwg.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLitManScopeProvider extends DelegatingScopeProvider {
}
