/*
 * generated by Xtext 2.21.0
 */
package org.xtext.htwg.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.htwg.litman.ui.internal.LitmanActivator;

public class LitManUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LitmanActivator.getInstance().getInjector("org.xtext.htwg.LitMan");
	}

}
