/*
 * generated by Xtext 2.21.0
 */
package org.xtext.htwg.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LitManUiModule extends AbstractLitManUiModule {

	public LitManUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
