/**
 * generated by Xtext 2.21.0
 */
package org.xtext.htwg.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.xtext.htwg.tests.LitManInjectorProvider;

@ExtendWith(InjectionExtension.class)
@InjectWith(LitManInjectorProvider.class)
@SuppressWarnings("all")
public class LitManParsingTest {
  @Inject
  private /* ParseHelper<Lit> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field LitManParsingTest.parseHelper refers to the missing type Lit"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
