/**
 * generated by Xtext 2.21.0
 */
package org.xtext.htwg.litMan;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Book</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.htwg.litMan.LitManPackage#getBook()
 * @model
 * @generated
 */
public interface Book extends LitTypes
{
} // Book
