/**
 * generated by Xtext 2.21.0
 */
package org.xtext.htwg.litMan;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Journal Article</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.htwg.litMan.JournalArticle#getVolume <em>Volume</em>}</li>
 *   <li>{@link org.xtext.htwg.litMan.JournalArticle#getIssue <em>Issue</em>}</li>
 * </ul>
 *
 * @see org.xtext.htwg.litMan.LitManPackage#getJournalArticle()
 * @model
 * @generated
 */
public interface JournalArticle extends LitTypes
{
  /**
   * Returns the value of the '<em><b>Volume</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Volume</em>' attribute.
   * @see #setVolume(int)
   * @see org.xtext.htwg.litMan.LitManPackage#getJournalArticle_Volume()
   * @model
   * @generated
   */
  int getVolume();

  /**
   * Sets the value of the '{@link org.xtext.htwg.litMan.JournalArticle#getVolume <em>Volume</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Volume</em>' attribute.
   * @see #getVolume()
   * @generated
   */
  void setVolume(int value);

  /**
   * Returns the value of the '<em><b>Issue</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Issue</em>' attribute.
   * @see #setIssue(int)
   * @see org.xtext.htwg.litMan.LitManPackage#getJournalArticle_Issue()
   * @model
   * @generated
   */
  int getIssue();

  /**
   * Sets the value of the '{@link org.xtext.htwg.litMan.JournalArticle#getIssue <em>Issue</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Issue</em>' attribute.
   * @see #getIssue()
   * @generated
   */
  void setIssue(int value);

} // JournalArticle
