/**
 * generated by Xtext 2.21.0
 */
package org.xtext.htwg.litMan;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List Authors</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.htwg.litMan.ListAuthors#getAuthors <em>Authors</em>}</li>
 * </ul>
 *
 * @see org.xtext.htwg.litMan.LitManPackage#getListAuthors()
 * @model
 * @generated
 */
public interface ListAuthors extends EObject
{
  /**
   * Returns the value of the '<em><b>Authors</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.htwg.litMan.Author}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Authors</em>' containment reference list.
   * @see org.xtext.htwg.litMan.LitManPackage#getListAuthors_Authors()
   * @model containment="true"
   * @generated
   */
  EList<Author> getAuthors();

} // ListAuthors
