/**
 * generated by Xtext 2.21.0
 */
package org.xtext.htwg.litMan;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.htwg.litMan.LitManPackage
 * @generated
 */
public interface LitManFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LitManFactory eINSTANCE = org.xtext.htwg.litMan.impl.LitManFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Lit Man</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Lit Man</em>'.
   * @generated
   */
  LitMan createLitMan();

  /**
   * Returns a new object of class '<em>Lit Types</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Lit Types</em>'.
   * @generated
   */
  LitTypes createLitTypes();

  /**
   * Returns a new object of class '<em>Book</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Book</em>'.
   * @generated
   */
  Book createBook();

  /**
   * Returns a new object of class '<em>Journal Article</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Journal Article</em>'.
   * @generated
   */
  JournalArticle createJournalArticle();

  /**
   * Returns a new object of class '<em>Author</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Author</em>'.
   * @generated
   */
  Author createAuthor();

  /**
   * Returns a new object of class '<em>List Authors</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>List Authors</em>'.
   * @generated
   */
  ListAuthors createListAuthors();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  LitManPackage getLitManPackage();

} //LitManFactory
