/**
 * generated by Xtext 2.21.0
 */
package org.xtext.htwg.litMan;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lit Man</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.htwg.litMan.LitMan#getLiteratur <em>Literatur</em>}</li>
 * </ul>
 *
 * @see org.xtext.htwg.litMan.LitManPackage#getLitMan()
 * @model
 * @generated
 */
public interface LitMan extends EObject
{
  /**
   * Returns the value of the '<em><b>Literatur</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.htwg.litMan.LitTypes}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Literatur</em>' containment reference list.
   * @see org.xtext.htwg.litMan.LitManPackage#getLitMan_Literatur()
   * @model containment="true"
   * @generated
   */
  EList<LitTypes> getLiteratur();

} // LitMan
