/**
 * generated by Xtext 2.21.0
 */
package org.xtext.htwg.litMan;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.htwg.litMan.LitManFactory
 * @model kind="package"
 * @generated
 */
public interface LitManPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "litMan";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/LitMan";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "litMan";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LitManPackage eINSTANCE = org.xtext.htwg.litMan.impl.LitManPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.htwg.litMan.impl.LitManImpl <em>Lit Man</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.htwg.litMan.impl.LitManImpl
   * @see org.xtext.htwg.litMan.impl.LitManPackageImpl#getLitMan()
   * @generated
   */
  int LIT_MAN = 0;

  /**
   * The feature id for the '<em><b>Literatur</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIT_MAN__LITERATUR = 0;

  /**
   * The number of structural features of the '<em>Lit Man</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIT_MAN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.htwg.litMan.impl.LitTypesImpl <em>Lit Types</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.htwg.litMan.impl.LitTypesImpl
   * @see org.xtext.htwg.litMan.impl.LitManPackageImpl#getLitTypes()
   * @generated
   */
  int LIT_TYPES = 1;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIT_TYPES__TITLE = 0;

  /**
   * The feature id for the '<em><b>Authors</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIT_TYPES__AUTHORS = 1;

  /**
   * The feature id for the '<em><b>Pages</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIT_TYPES__PAGES = 2;

  /**
   * The feature id for the '<em><b>Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIT_TYPES__DATE = 3;

  /**
   * The number of structural features of the '<em>Lit Types</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIT_TYPES_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.htwg.litMan.impl.BookImpl <em>Book</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.htwg.litMan.impl.BookImpl
   * @see org.xtext.htwg.litMan.impl.LitManPackageImpl#getBook()
   * @generated
   */
  int BOOK = 2;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOK__TITLE = LIT_TYPES__TITLE;

  /**
   * The feature id for the '<em><b>Authors</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOK__AUTHORS = LIT_TYPES__AUTHORS;

  /**
   * The feature id for the '<em><b>Pages</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOK__PAGES = LIT_TYPES__PAGES;

  /**
   * The feature id for the '<em><b>Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOK__DATE = LIT_TYPES__DATE;

  /**
   * The number of structural features of the '<em>Book</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOK_FEATURE_COUNT = LIT_TYPES_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.htwg.litMan.impl.JournalArticleImpl <em>Journal Article</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.htwg.litMan.impl.JournalArticleImpl
   * @see org.xtext.htwg.litMan.impl.LitManPackageImpl#getJournalArticle()
   * @generated
   */
  int JOURNAL_ARTICLE = 3;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOURNAL_ARTICLE__TITLE = LIT_TYPES__TITLE;

  /**
   * The feature id for the '<em><b>Authors</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOURNAL_ARTICLE__AUTHORS = LIT_TYPES__AUTHORS;

  /**
   * The feature id for the '<em><b>Pages</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOURNAL_ARTICLE__PAGES = LIT_TYPES__PAGES;

  /**
   * The feature id for the '<em><b>Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOURNAL_ARTICLE__DATE = LIT_TYPES__DATE;

  /**
   * The feature id for the '<em><b>Volume</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOURNAL_ARTICLE__VOLUME = LIT_TYPES_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Issue</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOURNAL_ARTICLE__ISSUE = LIT_TYPES_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Journal Article</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOURNAL_ARTICLE_FEATURE_COUNT = LIT_TYPES_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.htwg.litMan.impl.AuthorImpl <em>Author</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.htwg.litMan.impl.AuthorImpl
   * @see org.xtext.htwg.litMan.impl.LitManPackageImpl#getAuthor()
   * @generated
   */
  int AUTHOR = 4;

  /**
   * The feature id for the '<em><b>Firstname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTHOR__FIRSTNAME = 0;

  /**
   * The feature id for the '<em><b>Lastname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTHOR__LASTNAME = 1;

  /**
   * The number of structural features of the '<em>Author</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTHOR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.htwg.litMan.impl.ListAuthorsImpl <em>List Authors</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.htwg.litMan.impl.ListAuthorsImpl
   * @see org.xtext.htwg.litMan.impl.LitManPackageImpl#getListAuthors()
   * @generated
   */
  int LIST_AUTHORS = 5;

  /**
   * The feature id for the '<em><b>Authors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_AUTHORS__AUTHORS = 0;

  /**
   * The number of structural features of the '<em>List Authors</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_AUTHORS_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.htwg.litMan.LitMan <em>Lit Man</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lit Man</em>'.
   * @see org.xtext.htwg.litMan.LitMan
   * @generated
   */
  EClass getLitMan();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.htwg.litMan.LitMan#getLiteratur <em>Literatur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Literatur</em>'.
   * @see org.xtext.htwg.litMan.LitMan#getLiteratur()
   * @see #getLitMan()
   * @generated
   */
  EReference getLitMan_Literatur();

  /**
   * Returns the meta object for class '{@link org.xtext.htwg.litMan.LitTypes <em>Lit Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lit Types</em>'.
   * @see org.xtext.htwg.litMan.LitTypes
   * @generated
   */
  EClass getLitTypes();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.htwg.litMan.LitTypes#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see org.xtext.htwg.litMan.LitTypes#getTitle()
   * @see #getLitTypes()
   * @generated
   */
  EAttribute getLitTypes_Title();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.htwg.litMan.LitTypes#getAuthors <em>Authors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Authors</em>'.
   * @see org.xtext.htwg.litMan.LitTypes#getAuthors()
   * @see #getLitTypes()
   * @generated
   */
  EReference getLitTypes_Authors();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.htwg.litMan.LitTypes#getPages <em>Pages</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pages</em>'.
   * @see org.xtext.htwg.litMan.LitTypes#getPages()
   * @see #getLitTypes()
   * @generated
   */
  EAttribute getLitTypes_Pages();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.htwg.litMan.LitTypes#getDate <em>Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Date</em>'.
   * @see org.xtext.htwg.litMan.LitTypes#getDate()
   * @see #getLitTypes()
   * @generated
   */
  EAttribute getLitTypes_Date();

  /**
   * Returns the meta object for class '{@link org.xtext.htwg.litMan.Book <em>Book</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Book</em>'.
   * @see org.xtext.htwg.litMan.Book
   * @generated
   */
  EClass getBook();

  /**
   * Returns the meta object for class '{@link org.xtext.htwg.litMan.JournalArticle <em>Journal Article</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Journal Article</em>'.
   * @see org.xtext.htwg.litMan.JournalArticle
   * @generated
   */
  EClass getJournalArticle();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.htwg.litMan.JournalArticle#getVolume <em>Volume</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Volume</em>'.
   * @see org.xtext.htwg.litMan.JournalArticle#getVolume()
   * @see #getJournalArticle()
   * @generated
   */
  EAttribute getJournalArticle_Volume();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.htwg.litMan.JournalArticle#getIssue <em>Issue</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Issue</em>'.
   * @see org.xtext.htwg.litMan.JournalArticle#getIssue()
   * @see #getJournalArticle()
   * @generated
   */
  EAttribute getJournalArticle_Issue();

  /**
   * Returns the meta object for class '{@link org.xtext.htwg.litMan.Author <em>Author</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Author</em>'.
   * @see org.xtext.htwg.litMan.Author
   * @generated
   */
  EClass getAuthor();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.htwg.litMan.Author#getFirstname <em>Firstname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Firstname</em>'.
   * @see org.xtext.htwg.litMan.Author#getFirstname()
   * @see #getAuthor()
   * @generated
   */
  EAttribute getAuthor_Firstname();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.htwg.litMan.Author#getLastname <em>Lastname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Lastname</em>'.
   * @see org.xtext.htwg.litMan.Author#getLastname()
   * @see #getAuthor()
   * @generated
   */
  EAttribute getAuthor_Lastname();

  /**
   * Returns the meta object for class '{@link org.xtext.htwg.litMan.ListAuthors <em>List Authors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List Authors</em>'.
   * @see org.xtext.htwg.litMan.ListAuthors
   * @generated
   */
  EClass getListAuthors();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.htwg.litMan.ListAuthors#getAuthors <em>Authors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Authors</em>'.
   * @see org.xtext.htwg.litMan.ListAuthors#getAuthors()
   * @see #getListAuthors()
   * @generated
   */
  EReference getListAuthors_Authors();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  LitManFactory getLitManFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.htwg.litMan.impl.LitManImpl <em>Lit Man</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.htwg.litMan.impl.LitManImpl
     * @see org.xtext.htwg.litMan.impl.LitManPackageImpl#getLitMan()
     * @generated
     */
    EClass LIT_MAN = eINSTANCE.getLitMan();

    /**
     * The meta object literal for the '<em><b>Literatur</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIT_MAN__LITERATUR = eINSTANCE.getLitMan_Literatur();

    /**
     * The meta object literal for the '{@link org.xtext.htwg.litMan.impl.LitTypesImpl <em>Lit Types</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.htwg.litMan.impl.LitTypesImpl
     * @see org.xtext.htwg.litMan.impl.LitManPackageImpl#getLitTypes()
     * @generated
     */
    EClass LIT_TYPES = eINSTANCE.getLitTypes();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIT_TYPES__TITLE = eINSTANCE.getLitTypes_Title();

    /**
     * The meta object literal for the '<em><b>Authors</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIT_TYPES__AUTHORS = eINSTANCE.getLitTypes_Authors();

    /**
     * The meta object literal for the '<em><b>Pages</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIT_TYPES__PAGES = eINSTANCE.getLitTypes_Pages();

    /**
     * The meta object literal for the '<em><b>Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIT_TYPES__DATE = eINSTANCE.getLitTypes_Date();

    /**
     * The meta object literal for the '{@link org.xtext.htwg.litMan.impl.BookImpl <em>Book</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.htwg.litMan.impl.BookImpl
     * @see org.xtext.htwg.litMan.impl.LitManPackageImpl#getBook()
     * @generated
     */
    EClass BOOK = eINSTANCE.getBook();

    /**
     * The meta object literal for the '{@link org.xtext.htwg.litMan.impl.JournalArticleImpl <em>Journal Article</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.htwg.litMan.impl.JournalArticleImpl
     * @see org.xtext.htwg.litMan.impl.LitManPackageImpl#getJournalArticle()
     * @generated
     */
    EClass JOURNAL_ARTICLE = eINSTANCE.getJournalArticle();

    /**
     * The meta object literal for the '<em><b>Volume</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JOURNAL_ARTICLE__VOLUME = eINSTANCE.getJournalArticle_Volume();

    /**
     * The meta object literal for the '<em><b>Issue</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JOURNAL_ARTICLE__ISSUE = eINSTANCE.getJournalArticle_Issue();

    /**
     * The meta object literal for the '{@link org.xtext.htwg.litMan.impl.AuthorImpl <em>Author</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.htwg.litMan.impl.AuthorImpl
     * @see org.xtext.htwg.litMan.impl.LitManPackageImpl#getAuthor()
     * @generated
     */
    EClass AUTHOR = eINSTANCE.getAuthor();

    /**
     * The meta object literal for the '<em><b>Firstname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AUTHOR__FIRSTNAME = eINSTANCE.getAuthor_Firstname();

    /**
     * The meta object literal for the '<em><b>Lastname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AUTHOR__LASTNAME = eINSTANCE.getAuthor_Lastname();

    /**
     * The meta object literal for the '{@link org.xtext.htwg.litMan.impl.ListAuthorsImpl <em>List Authors</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.htwg.litMan.impl.ListAuthorsImpl
     * @see org.xtext.htwg.litMan.impl.LitManPackageImpl#getListAuthors()
     * @generated
     */
    EClass LIST_AUTHORS = eINSTANCE.getListAuthors();

    /**
     * The meta object literal for the '<em><b>Authors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIST_AUTHORS__AUTHORS = eINSTANCE.getListAuthors_Authors();

  }

} //LitManPackage
