/**
 * generated by Xtext 2.21.0
 */
package org.xtext.htwg.litMan;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lit Types</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.htwg.litMan.LitTypes#getTitle <em>Title</em>}</li>
 *   <li>{@link org.xtext.htwg.litMan.LitTypes#getAuthors <em>Authors</em>}</li>
 *   <li>{@link org.xtext.htwg.litMan.LitTypes#getPages <em>Pages</em>}</li>
 *   <li>{@link org.xtext.htwg.litMan.LitTypes#getDate <em>Date</em>}</li>
 * </ul>
 *
 * @see org.xtext.htwg.litMan.LitManPackage#getLitTypes()
 * @model
 * @generated
 */
public interface LitTypes extends EObject
{
  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see org.xtext.htwg.litMan.LitManPackage#getLitTypes_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link org.xtext.htwg.litMan.LitTypes#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Authors</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Authors</em>' containment reference.
   * @see #setAuthors(ListAuthors)
   * @see org.xtext.htwg.litMan.LitManPackage#getLitTypes_Authors()
   * @model containment="true"
   * @generated
   */
  ListAuthors getAuthors();

  /**
   * Sets the value of the '{@link org.xtext.htwg.litMan.LitTypes#getAuthors <em>Authors</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Authors</em>' containment reference.
   * @see #getAuthors()
   * @generated
   */
  void setAuthors(ListAuthors value);

  /**
   * Returns the value of the '<em><b>Pages</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pages</em>' attribute.
   * @see #setPages(String)
   * @see org.xtext.htwg.litMan.LitManPackage#getLitTypes_Pages()
   * @model
   * @generated
   */
  String getPages();

  /**
   * Sets the value of the '{@link org.xtext.htwg.litMan.LitTypes#getPages <em>Pages</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pages</em>' attribute.
   * @see #getPages()
   * @generated
   */
  void setPages(String value);

  /**
   * Returns the value of the '<em><b>Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Date</em>' attribute.
   * @see #setDate(String)
   * @see org.xtext.htwg.litMan.LitManPackage#getLitTypes_Date()
   * @model
   * @generated
   */
  String getDate();

  /**
   * Sets the value of the '{@link org.xtext.htwg.litMan.LitTypes#getDate <em>Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Date</em>' attribute.
   * @see #getDate()
   * @generated
   */
  void setDate(String value);

} // LitTypes
