/*
 * generated by Xtext 2.21.0
 */
package org.xtext.htwg.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.htwg.LitManRuntimeModule;
import org.xtext.htwg.LitManStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class LitManIdeSetup extends LitManStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new LitManRuntimeModule(), new LitManIdeModule()));
	}
	
}
