/**
 * generated by Xtext 2.21.0
 */
package org.xtext.htwg.litMan.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.htwg.litMan.Book;
import org.xtext.htwg.litMan.LitManPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Book</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BookImpl extends LitTypesImpl implements Book
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BookImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LitManPackage.Literals.BOOK;
  }

} //BookImpl
