/**
 * generated by Xtext 2.21.0
 */
package org.xtext.htwg.litMan.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.htwg.litMan.Author;
import org.xtext.htwg.litMan.ListAuthors;
import org.xtext.htwg.litMan.LitManPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>List Authors</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.htwg.litMan.impl.ListAuthorsImpl#getAuthors <em>Authors</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ListAuthorsImpl extends MinimalEObjectImpl.Container implements ListAuthors
{
  /**
   * The cached value of the '{@link #getAuthors() <em>Authors</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAuthors()
   * @generated
   * @ordered
   */
  protected EList<Author> authors;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ListAuthorsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LitManPackage.Literals.LIST_AUTHORS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Author> getAuthors()
  {
    if (authors == null)
    {
      authors = new EObjectContainmentEList<Author>(Author.class, this, LitManPackage.LIST_AUTHORS__AUTHORS);
    }
    return authors;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LitManPackage.LIST_AUTHORS__AUTHORS:
        return ((InternalEList<?>)getAuthors()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LitManPackage.LIST_AUTHORS__AUTHORS:
        return getAuthors();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LitManPackage.LIST_AUTHORS__AUTHORS:
        getAuthors().clear();
        getAuthors().addAll((Collection<? extends Author>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LitManPackage.LIST_AUTHORS__AUTHORS:
        getAuthors().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LitManPackage.LIST_AUTHORS__AUTHORS:
        return authors != null && !authors.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ListAuthorsImpl
