/**
 * generated by Xtext 2.21.0
 */
package org.xtext.htwg.litMan.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.htwg.litMan.LitMan;
import org.xtext.htwg.litMan.LitManPackage;
import org.xtext.htwg.litMan.LitTypes;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Lit Man</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.htwg.litMan.impl.LitManImpl#getLiteratur <em>Literatur</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LitManImpl extends MinimalEObjectImpl.Container implements LitMan
{
  /**
   * The cached value of the '{@link #getLiteratur() <em>Literatur</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLiteratur()
   * @generated
   * @ordered
   */
  protected EList<LitTypes> literatur;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LitManImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LitManPackage.Literals.LIT_MAN;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<LitTypes> getLiteratur()
  {
    if (literatur == null)
    {
      literatur = new EObjectContainmentEList<LitTypes>(LitTypes.class, this, LitManPackage.LIT_MAN__LITERATUR);
    }
    return literatur;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LitManPackage.LIT_MAN__LITERATUR:
        return ((InternalEList<?>)getLiteratur()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LitManPackage.LIT_MAN__LITERATUR:
        return getLiteratur();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LitManPackage.LIT_MAN__LITERATUR:
        getLiteratur().clear();
        getLiteratur().addAll((Collection<? extends LitTypes>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LitManPackage.LIT_MAN__LITERATUR:
        getLiteratur().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LitManPackage.LIT_MAN__LITERATUR:
        return literatur != null && !literatur.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //LitManImpl
